ID CITY STATE LAT_N LONG_W
794 Kissee Mills MO 140 73
824 Loma Mar CA 49 131
603 Sandy Hook CT 72 148
478 Tipton IN 34 98
619 Arlington CO 75 93
711 Turner AR 50 101
839 Slidell LA 85 152
.
.
.
754 South Haven MI 145 53
144 Eskridge KS 1

SELECT CITY, STATE
FROM STATION;

SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

SELECT (count(CITY) - count(DISTINCT CITY)) as DIFFERENCE
FROM STATION;

(
SELECT CITY, length(CITY) as len
FROM STATION
ORDER BY len, CITY 
LIMIT 1
)
UNION
(
SELECT CITY, length(CITY) as len
FROM STATION
ORDER BY len DESC, CITY 
LIMIT 1
)

SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%';

SELECT DISTINCT CITY
FROM STATION
WHERE REGEXP_LIKE(CITY, '^[aeiou].*[aeiou]$', 'i');

SELECT DISTINCT CITY
FROM STATION
WHERE NOT REGEXP_LIKE(CITY, '^[aeiou]', 'i')
AND NOT REGEXP_LIKE(CITY, '[aeiou]$', 'i');

SELECT DISTINCT CITY
FROM STATION
WHERE NOT REGEXP_LIKE(CITY, '[aeiou]$', 'i');